/*** Generated by streamline 0.10.1 (generators) - DO NOT EDIT ***/var galaxy = require("streamline/lib/generators/runtime"); (galaxy.unstar(function*(_) { /**
 * Copyright (c) 2011 Bruno Jouhier <bruno.jouhier@sage.com>
 *
 * Permission is hereby granted, free of charge, to any person
 * obtaining a copy of this software and associated documentation
 * files (the "Software"), to deal in the Software without
 * restriction, including without limitation the rights to use,
 * copy, modify, merge, publish, distribute, sublicense, and/or sell
 * copies of the Software, and to permit persons to whom the
 * Software is furnished to do so, subject to the following
 * conditions:
 *
 * The above copyright notice and this permission notice shall be
 * included in all copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND,
 * EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES
 * OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND
 * NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT
 * HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY,
 * WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING
 * FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR
 * OTHER DEALINGS IN THE SOFTWARE.
 *
 */

/// 
/// # Flow control utilities
///  
/// `var flows = require('streamline/lib/util/flows')`
/// 
(function(exports) {
	"use strict";
	var globals = require('streamline/lib/globals');
	var dir = 'streamline/lib/' + globals.runtime;
	var builtins = require(dir + '/builtins');
	/// !nodoc
	/// Obsolete API
	/// 
	/// This API is obsolete. Use `array.forEach_`, `array.map_`, ... instead.
	/// 
	/// * `flows.each(_, array, fn, [thisObj])`  
	///   applies `fn` sequentially to the elements of `array`.  
	///   `fn` is called as `fn(_, elt, i)`.
	exports.each = galaxy.unstar(function*(_, array, fn, thisObj) {
		return (array && array.length) ? (yield galaxy.invoke(array, "forEach_", [_, fn, thisObj], 0)) : undefined;
	}, 0);
	/// * `result = flows.map(_, array, fn, [thisObj])`  
	///   transforms `array` by applying `fn` to each element in turn.  
	///   `fn` is called as `fn(_, elt, i)`.
	exports.map = galaxy.unstar(function*(_, array, fn, thisObj) {
		return array ? (yield galaxy.invoke(array, "map_", [_, fn, thisObj], 0)) : array;
	}, 0);
	/// * `result = flows.filter(_, array, fn, [thisObj])`  
	///   generates a new array that only contains the elements that satisfy the `fn` predicate.  
	///   `fn` is called as `fn(_, elt)`.
	exports.filter = galaxy.unstar(function*(_, array, fn, thisObj) {
		return array ? (yield galaxy.invoke(array, "filter_", [_, fn, thisObj], 0)) : array;
	}, 0);
	/// * `bool = flows.every(_, array, fn, [thisObj])`  
	///   returns true if `fn` is true on every element (if `array` is empty too).  
	///   `fn` is called as `fn(_, elt)`.
	exports.every = galaxy.unstar(function*(_, array, fn, thisObj) {
		return array ? (yield galaxy.invoke(array, "every_", [_, fn, thisObj], 0)) : undefined;
	}, 0);
	/// * `bool = flows.some(_, array, fn, [thisObj])`  
	///   returns true if `fn` is true for at least one element.  
	///   `fn` is called as `fn(_, elt)`.
	exports.some = galaxy.unstar(function*(_, array, fn, thisObj) {
		return array ? (yield galaxy.invoke(array, "some_", [_, fn, thisObj], 0)) : undefined;
	}, 0);
	/// * `result = flows.reduce(_, array, fn, val, [thisObj])`  
	///   reduces by applying `fn` to each element.  
	///   `fn` is called as `val = fn(_, val, elt, i, array)`.
	exports.reduce = galaxy.unstar(function*(_, array, fn, v, thisObj) {
		return array ? (yield galaxy.invoke(array, "reduce_", [_, fn, v, thisObj], 0)) : v;
	}, 0);
	/// * `result = flows.reduceRight(_, array, fn, val, [thisObj])`  
	///   reduces from end to start by applying `fn` to each element.  
	///   `fn` is called as `val = fn(_, val, elt, i, array)`.
	exports.reduceRight = galaxy.unstar(function*(_, array, fn, v, thisObj) {
		return array ? (yield galaxy.invoke(array, "reduceRight_", [_, fn, v, thisObj], 0)) : v;
	}, 0);

	/// * `array = flows.sort(_, array, compare, [beg], [end])`  
	///   sorts the array.  
	///   `compare` is called as `cmp = compare(_, elt1, elt2)`
	///   
	///   Note: this function _changes_ the original array (and returns it)
	exports.sort = galaxy.unstar(function*(_, array, compare, beg, end) {
		return array ? (yield galaxy.invoke(array, "sort_", [_, compare, beg, end], 0)) : array;
	}, 0);
	/// 
	/// ## Object utility (obsolete)
	/// 
	/// This API is obsolete. Use `Object.keys(obj).forEach_` instead.
	/// 
	/// * `flows.eachKey(_, obj, fn)`  
	///   calls `fn(_, key, obj[key])` for every `key` in `obj`.
	exports.eachKey = galaxy.unstar(function*(_, obj, fn, thisObj) {
		return (yield galaxy.invoke((obj ? Object.keys(obj) : []), "forEach_", [_, galaxy.unstar(function*(_, elt) {
			(yield galaxy.invoke(fn, "call", [thisObj, _, elt, obj[elt]], 1));
		}, 0)], 0));
	}, 0);
	// deprecated -- don't document 
	exports.spray = function(fns, max) {
		return new

		function() {
			var funnel = exports.funnel(max);
			this.collect = galaxy.unstar(function*(_, count, trim) {
				return (yield galaxy.invoke((function(callback) {
					if (typeof(callback) != "function") throw new Error("invalid call to collect: no callback");
					var results = trim ? [] : new Array(fns.length);
					count = count < 0 ? fns.length : Math.min(count, fns.length);
					if (count == 0) return callback(null, results);
					var collected = 0;
					for (var i = 0; i < fns.length; i++) {
						(function(i) {
							funnel(  function(err, result) {
								if (err) return callback(err);
								if (trim) results.push(result);
								else results[i] = result;
								if (++collected == count) return callback(null, results);
							}, fns[i]);
						})(i);
					}
				}), "call", [this, _], 1));
			}, 0);
			this.collectOne = galaxy.unstar(function*(_) {
				var result = (yield galaxy.invoke(this, "collect", [_, 1, true], 0));
				return result && result[0];
			}, 0);
			this.collectAll = galaxy.unstar(function*(_) {
				return (yield galaxy.invoke(this, "collect", [_, -1, false], 0));
			}, 0);
		};

	};

	
	/// * `fun = flows.funnel(max)`  
	///   limits the number of concurrent executions of a given code block.
	/// 
	/// The `funnel` function is typically used with the following pattern:
	/// 
	/// ``` javascript
	/// // somewhere
	/// var myFunnel = flows.funnel(10); // create a funnel that only allows 10 concurrent executions.
	/// 
	/// // elsewhere
	/// myFunnel(_, function(_) { /* code with at most 10 concurrent executions */ });
	/// ```
	/// 
	/// The `diskUsage2.js` example demonstrates how these calls can be combined to control concurrent execution.
	/// 
	/// The `funnel` function can also be used to implement critical sections. Just set funnel's `max` parameter to 1.
	/// 
	/// If `max` is set to 0, a default number of parallel executions is allowed. 
	/// This default number can be read and set via `flows.funnel.defaultSize`.  
	/// If `max` is negative, the funnel does not limit the level of parallelism.
	/// 
	/// The funnel can be closed with `fun.close()`.  
	/// When a funnel is closed, the operations that are still in the funnel will continue but their callbacks
	/// won't be called, and no other operation will enter the funnel.
	exports.funnel = builtins.funnel;

	/// 
	/// * `results = flows.collect(_, futures)`  
	///   collects the results of an array of futures
	exports.collect = galaxy.unstar(function*(_, futures) {
		return futures && (yield galaxy.invoke(futures, "map_", [_, galaxy.unstar(function*(_, future) {
			return (yield galaxy.invoke(null, future, [_], 0));
		}, 0)], 0));
	}, 0);

	// Obsolete API - use require('streamline/lib/globals').context instead
	var globals = require("streamline/lib/globals");
	exports.setContext = function(ctx) {
		var old = globals.context;
		globals.context = ctx;
		return old;
	};
	exports.getContext = function() {
		return globals.context;
	};

	/// 
	/// * `flows.nextTick(_)`  
	///   `nextTick` function for both browser and server.  
	///   Aliased to `process.nextTick` on the server side.
	var nextTick = typeof process === "object" && typeof process.nextTick === "function" ? process.nextTick : function(cb) {
		cb();
	};

	exports.nextTick =  galaxy.unstar(function*(_) {
		(yield galaxy.invoke(null, nextTick, [_], 0));
	}, 0);

	exports.setTimeout = function(fn, millis) {
		return setTimeout(function() {
			fn(false);
		}, millis);
	};

	exports.setInterval = function(fn, millis) {
		return setInterval(function() {
			fn(false);
		}, millis);
	};

	exports.eventHandler = function(fn) {
		return function() {
			var that = this;
			var args = Array.prototype.slice(arguments, 0);
			return galaxy.unstar((function*(_) {
				return (yield galaxy.invoke(fn, "apply_", [_, that, args, 0], 0));
			}), 0)(  function(err) {
				if (err) throw err;
			});
		};
	};

	//   Obsolete. Use `fn.apply_` instead.
	exports.apply = galaxy.unstar(function* apply(_, fn, thisObj, args, index) {
		return (yield galaxy.invoke(fn, "apply_", [_, thisObj, args, index], 0));
	}, 0);

	exports.callWithTimeout = galaxy.streamlinify(function(cb, fn, millis) {
			var tid = setTimeout(function() {
				if (cb) {
					var ex = new Error("timeout");
					ex.code = "ETIMEOUT";
					ex.errno = "ETIMEOUT";
					cb(ex);
					cb = null;
				}
			}, millis);
			fn(  function(err, result) {
				if (cb) {
					clearTimeout(tid);
					cb(err, result);
					cb = null;
				}
			});
	}, 0);


})(typeof exports !== 'undefined' ? exports : (Streamline.flows = Streamline.flows || {}));

}, 0).call(this, function(err) {
  if (err) throw err;
}));
